# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
    ports:
      - 3305:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3307:80
    environment:
      - PMA_ARBITRARY=1